apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  selector:
    app: product-service
  type: NodePort
  ports:
  - name: productservice
    port: 3000
    targetPort: 3000
    protocol: TCP